[icons]  
name = "awesome"
[icons.overrides]
cpu = ""
update = ""

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#81a1c1"
idle_fg = "#4c566a"
info_bg = "#7995a1"
info_fg = "#4c566a"
good_bg = "#a3be8c"
good_fg = "#4c566a"
warning_bg = "#ebcb8b"
warning_fg = "#4c566a"
critical_bg = "#bf616a"
critical_fg = "#4c566a"

[[block]]
block = "docker"
interval = 2
format = "{running}/{total}"

[[block]]
block = "pacman"
interval = 10

[[block]]
block = "net"
device = "eno2"
ssid = false
interval = 5

[[block]]
block = "net"
device = "wlo1"
ssid = true
interval = 5

[[block]]
block = "disk_space"
path = "/home"
alias = " "
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "time"
interval = 60
format = "%a %d-%m | %R"

[[block]]
block = "sound"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
on_collapsed_click = "spotify"

[[block]]
block = "battery"
interval = 30
format = "{percentage}%"

